name = "ControlSystemsTools"
uuid = "66f4a95a-6313-4021-884f-42827225fcdd"
authors = ["F. Capolupo"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
